// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR6qfQ-E_5CSjH1bGIyPfWArUPFxTKoC0',
    appId: '1:688369231954:android:a1a6d84015a44ef2c1578b',
    messagingSenderId: '688369231954',
    projectId: 'crypto-tom',
    databaseURL: 'https://crypto-tom-default-rtdb.firebaseio.com',
    storageBucket: 'crypto-tom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwtnqSqGLmFyg-cdxcNT9AXv44DiDjrks',
    appId: '1:688369231954:ios:851b11a3359577dcc1578b',
    messagingSenderId: '688369231954',
    projectId: 'crypto-tom',
    databaseURL: 'https://crypto-tom-default-rtdb.firebaseio.com',
    storageBucket: 'crypto-tom.appspot.com',
    iosClientId: '688369231954-bitrlk3ohoqatlf219q7k9i99m0q926j.apps.googleusercontent.com',
    iosBundleId: 'nofal.horsly',
  );
}
